# Generated by Django 2.1.15 on 2020-11-26 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FossilFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FossilPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picturepath', models.CharField(max_length=128, verbose_name='图片链接')),
                ('picturetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='拍摄时间')),
                ('picturelocation', models.CharField(max_length=128, verbose_name='拍摄地点')),
                ('document', models.CharField(max_length=140, verbose_name='描述信息')),
                ('reconstruction', models.CharField(max_length=128, verbose_name='重建结果')),
            ],
        ),
        migrations.CreateModel(
            name='MyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收藏时间')),
                ('fossil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FossilPicture', verbose_name='化石ID')),
            ],
        ),
        migrations.CreateModel(
            name='MyFossil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('fossil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FossilPicture', verbose_name='化石ID')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciesname', models.CharField(max_length=20, verbose_name='物种名')),
                ('speciescover', models.CharField(max_length=200, verbose_name='封面图片')),
                ('specieslocation', models.CharField(max_length=20, verbose_name='谱系位置')),
                ('epoch', models.CharField(max_length=20, verbose_name='生存时期')),
                ('describe', models.CharField(max_length=140, verbose_name='详细描述')),
                ('picture', models.CharField(max_length=128, verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=11, verbose_name='用户名')),
                ('usericon', models.CharField(max_length=128, verbose_name='用户头像')),
                ('status', models.CharField(max_length=20, verbose_name='身份')),
                ('institution', models.CharField(max_length=20, verbose_name='单位')),
            ],
        ),
        migrations.AddField(
            model_name='myfossil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo', verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='mycollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo', verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='fossilpicture',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SpeciesGuide', verbose_name='物种名称'),
        ),
        migrations.AddField(
            model_name='fossilfamily',
            name='fossil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FossilPicture', verbose_name='化石ID'),
        ),
        migrations.AddField(
            model_name='fossilfamily',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo', verbose_name='用户ID'),
        ),
    ]
