# Generated by Django 2.1.15 on 2020-12-14 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.CharField(max_length=20, verbose_name='内容')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
        ),
    ]
