# Generated by Django 2.1.15 on 2021-01-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconstrucationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie', models.CharField(max_length=20, verbose_name='物种')),
                ('modelpath', models.CharField(max_length=128, verbose_name='模型链接')),
            ],
        ),
        migrations.AlterField(
            model_name='fossilpicture',
            name='reconstruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ReconstrucationModel', verbose_name='模型连接'),
        ),
    ]
