# Generated by Django 2.1.15 on 2021-01-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210117_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconstrucationmodel',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SpeciesGuide', verbose_name='物种ID'),
        ),
    ]
