# Generated by Django 2.1.15 on 2021-02-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210125_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adverstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=128, verbose_name='图片链接')),
                ('path', models.CharField(max_length=128, verbose_name='链接')),
            ],
        ),
        migrations.CreateModel(
            name='StudyAdverstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=128, verbose_name='图片链接')),
                ('path', models.CharField(max_length=128, verbose_name='链接')),
            ],
        ),
    ]
