# Generated by Django 3.2.13 on 2022-05-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_adverstation_studyadverstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('imagecover', models.CharField(max_length=200, verbose_name='封面图片')),
                ('url', models.CharField(max_length=200, verbose_name='新闻链接')),
                ('source', models.CharField(max_length=20, verbose_name='新闻来源')),
            ],
        ),
    ]
