# Generated by Django 3.2.13 on 2022-05-13 02:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_newsreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='标题')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('picturepath', models.TextField(verbose_name='图片路径')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo', verbose_name='用户ID')),
            ],
        ),
    ]
