# Generated by Django 3.2.13 on 2022-05-13 03:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyName', models.CharField(max_length=128, verbose_name='回复名')),
                ('content', models.CharField(max_length=128, verbose_name='回复内容')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publish', verbose_name='所属文章')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userinfo', verbose_name='用户ID')),
            ],
        ),
    ]
