# Generated by Django 3.2.13 on 2022-05-13 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='publish',
        ),
        migrations.AddField(
            model_name='publish',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.comment', verbose_name='评论'),
            preserve_default=False,
        ),
    ]
