# Generated by Django 3.2.13 on 2022-05-13 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220513_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='publish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.publish', verbose_name='所属文章'),
            preserve_default=False,
        ),
    ]
