# Generated by Django 3.2.13 on 2022-05-13 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220513_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replyName',
        ),
        migrations.AddField(
            model_name='comment',
            name='replyUser',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='replyUser', to='app.userinfo', verbose_name='回复人id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commentUser', to='app.userinfo', verbose_name='用户ID'),
        ),
    ]
