# Generated by Django 3.2.13 on 2022-05-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='isDelete',
            field=models.BooleanField(default=True, verbose_name='是否删除'),
        ),
    ]
